services:
  qbittorrent-nox:
    image: qbittorrent-nox-warp:latest
    # for debugging
    cap_add:
      - NET_ADMIN
      #- SYS_PTRACE
    device_cgroup_rules:
      - 'c 10:200 rwm'
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    container_name: qbittorrent-nox
    environment:
      #- PAGID=10000
      #- PGID=1000
      #- PUID=1000
      - QBT_LEGAL_NOTICE=confirm
      - QBT_WEBUI_PORT=80
      - WARP_SLEEP=5
      #- TZ=UTC
      #- UMASK=022
    # image: qbittorrentofficial/qbittorrent-nox:${QBT_VERSION}
    ports:
      # for bittorrent traffic
      - 6881:6881/tcp
      - 6881:6881/udp
      # for WebUI
      - 80:80/tcp
    # read_only: true
    stop_grace_period: 30m
    # tmpfs:
    #   - /tmp
    tty: true
    # volumes:
    #   - ${QBT_CONFIG_PATH}:/config
    #   - ${QBT_DOWNLOADS_PATH}:/downloads
