name: Build and publish Docker image

on:
  workflow_dispatch:  # trigger it manually

permissions: {}

env:
  QBT_VERSION: "5.1.0"

  # This is a positive integer number that allows to differentiate between consecutive builds of the same qBittorrent version.
  # When `QBT_VERSION` is incremented, this value must reset to 1.
  TAG_RELEASE_NUMBER: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            QBT_VERSION=${{ env.QBT_VERSION }}
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/sawntoe/qbittorrent-nox-warp:latest
            ghcr.io/sawntoe/docker-qbittorrent-nox-warp:latest
            ghcr.io/sawntoe/qbittorrent-nox-warp:${{ env.QBT_VERSION }}
            ghcr.io/sawntoe/docker-qbittorrent-nox-warp:${{ env.QBT_VERSION }}
            ghcr.io/sawntoe/qbittorrent-nox-warp:${{ env.QBT_VERSION }}-${{ env.TAG_RELEASE_NUMBER }}
            ghcr.io/sawntoe/docker-qbittorrent-nox-warp:${{ env.QBT_VERSION }}-${{ env.TAG_RELEASE_NUMBER }}
